server:
#  端口号
  port: 8081
  tomcat:
    max-http-form-post-size: -1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oos?serverTimezone=UTC&amp&useUnicode=true&amp&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
#      连接池名
      pool-name: DateHikariCP
#      最小空闲连接数
      minimum-idle: 5
#      最大连接数
      maximum-pool-size: 10
#      自动提交
      auto-commit: true
#      测试链接是否可用查询语句
      connection-test-query: SELECT 1
  redis:
#    超时时间
    timeout: 10000ms
#    服务器地址
    host: 192.168.191.128
#    服务器端口
    port: 6379
#    数据库
    database: 0
#    密码
    password: 123456
    lettuce:
      pool:
#        最大连接数
        max-active: 1024
#        最大连接阻塞等待时间
        max-wait: 10000ms
#        最大空闲连接数
        max-idle: 200
#        最小空闲连接数
        min-idle: 5
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
#  mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
#  数据返回类型别名
  type-aliases-package: com.yuzi.server.pojo
  configuration:
#    自动驼峰命名
    map-underscore-to-camel-case: false

#Mybatis SQL 打印
logging:
  level:
    com.yuzi.server.mapper: debug

jwt:
#  JWT存储的请求头
  tokenHeader: Authorization
#  JWT加解密使用的密钥
  secret: oos-secret
#  JWT超期限时间
  expiration: 604800
#  JWT负载中拿到开开头
  tokenHead: Bearer

